name: build

on: [push, pull_request]

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy, rustfmt

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-targets

    - name: Test
      if: matrix.toolchain != 'nightly'
      run: cargo test --workspace

    - name: Test
      if: matrix.toolchain == 'nightly'
      run: cargo test --workspace --features _bytes
