name: build

on: [push, pull_request]

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      run: |
        rustup set profile default
        rustup toolchain install ${{ matrix.toolchain }}
        rustup override set ${{ matrix.toolchain }}

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --workspace

    - name: Test
      run: cargo test --workspace
